version: '2'
services:
  influxdb:
    image: influxdb:1.8
    ports:
      - '8086:8086'
    volumes:
      - ./influx/influxdb_data:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=siklu
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
  grafana:
    image: grafana/grafana:8.5.0
    ports:
      - '3000:3000'

